{% set goname = "github.com/fullstorydev/grpcurl" %}
{% set version = "1.9.3" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: bb555087f279af156159c86d4d3d5dd3f2991129e4cd6b09114e6851a679340d

build:
  script:
    - go build -trimpath -ldflags "-s -w -X main.version=v{{ version }}" -o $PREFIX/bin/ ./cmd/{{ name }}/  # [unix]
    - go build -trimpath -ldflags "-s -w -X main.version=v{{ version }}" -o %LIBRARY_BIN%/ ./cmd/{{ name }}/  # [win]
    - go-licenses save . --save_path="./license-files/"
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - {{ name }} -version

about:
  home: https://{{ goname }}
  summary: 'Like cURL, but for gRPC: Command-line tool for interacting with gRPC servers'
  description: |
    grpcurl is a command-line tool that lets you interact with gRPC servers. It's basically curl for gRPC servers.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - license-files/

extra:
  recipe-maintainers:
    - seowalex
